version: '3.8'
services:
  # To have Database instance
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: fx-data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # fx-warehouse instance after building the image
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fx-warehouse
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fx-data
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  db_data: